@host = http://localhost:5201

### 회원가입
POST {{host}}/register
Content-Type: application/json

{
    "nickname": "Iory",
    "password": "q1w2e3r4"
}

###

### 로그인
POST {{host}}/login
Content-Type: application/json

{
    "nickname": "Iory",
    "password": "q1w2e3r4"
}

###

### 플레이어 생성
POST {{host}}/players
Content-Type: application/json

{
    "nickname": ""
}

###

### Refrest 토큰 생성
POST {{host}}/refresh
Content-Type: application/json

{
    "PlayerId": 14,
    "RefreshToken": "nUn5TN8v1W4eEsuILdSQwFacvZSoPKUgEtfozAIxb7Te3gk1ExE2frKmLzPDYwCl6ZT97Nka0S9uJFi0CL5b6g=="
}

### 내 정보 조회 (JWT 필요)
GET {{host}}/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjE0IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IklvcnkiLCJleHAiOjE3Nzk5NTkxNTYsImlzcyI6ImJsdWVTZXJ2ZXIiLCJhdWQiOiJibHVlU2VydmVyIn0.P_OfI--30OWejh6xIl21IPjdnSE-y4OGupFxNW1xH8k

###

### 플레이어 조회
GET {{host}}/players/0