input {
  beats {
    port => 5044
  }
}

filter {
  json {
    source => "message"
    target => "[@metadata][application]"
    tag_on_failure => ["_blue_server_json_parse_failure"]
  }

  if "_blue_server_json_parse_failure" not in [tags] {
    date {
      match => ["[@metadata][application][Timestamp]", "ISO8601"]
      target => "@timestamp"
    }

    mutate {
      replace => {
        "message" => "%{[@metadata][application][Message]}"
      }
      add_field => {
        "[event][code]" => "%{[@metadata][application][EventId]}"
        "[log][level]" => "%{[@metadata][application][LogLevel]}"
        "[log][logger]" => "%{[@metadata][application][Category]}"
      }
      rename => {
        "[@metadata][application][State]" => "[blue_server][state]"
        "[@metadata][application][Scopes]" => "[blue_server][scopes]"
      }
    }
  }

  mutate {
    add_field => {
      "[event][dataset]" => "%{[service][name]}.application"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "blue-server-logs-%{+YYYY.MM.dd}"
    ilm_enabled => false
    template => "/usr/share/logstash/templates/blue-server-logs.json"
    template_api => "composable"
    template_name => "blue-server-logs"
    template_overwrite => true
  }
}
