<Project Sdk="Microsoft.NET.Sdk.Worker">

  <ItemGroup>
    <ProjectReference Include="..\blueServer.Grains\blueServer.Grains.csproj" />
    <ProjectReference Include="..\..\blueServer.Infrastructure\blueServer.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Elastic.Apm.EntityFrameworkCore" Version="1.34.5" />
    <PackageReference Include="Elastic.Apm.Extensions.Hosting" Version="1.34.5" />
    <PackageReference Include="Microsoft.Orleans.Clustering.Redis" Version="10.2.1" />
    <PackageReference Include="Microsoft.Orleans.Hosting.Kubernetes" Version="10.2.1" />
    <PackageReference Include="Microsoft.Orleans.Server" Version="10.2.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
