// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using blueServer.Infrastructure;

#nullable disable

namespace blueServer.Infrastructure.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260904074052_AddCurrencyChangeLogs")]
    partial class AddCurrencyChangeLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("blueServer.Domain.Entities.CharacterTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CharacterTemplates");
                });

            modelBuilder.Entity("blueServer.Domain.Entities.CurrencyChangeLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("integer");

                    b.Property<int>("BalanceBefore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrencyType")
                        .HasColumnType("integer");

                    b.Property<int>("Delta")
                        .HasColumnType("integer");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("ReasonType")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<long?>("RewardGrantRecordId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("RewardGrantRecordId");

                    b.HasIndex("PlayerId", "CreatedAt", "Id");

                    b.HasIndex("PlayerId", "RequestId", "CurrencyType")
                        .IsUnique();

                    b.ToTable("CurrencyChangeLogs", t =>
                        {
                            t.HasCheckConstraint("CK_CurrencyChangeLogs_BalanceAfter_NonNegative", "\"BalanceAfter\" >= 0");

                            t.HasCheckConstraint("CK_CurrencyChangeLogs_BalanceBefore_NonNegative", "\"BalanceBefore\" >= 0");

                            t.HasCheckConstraint("CK_CurrencyChangeLogs_Balance_Consistent", "\"BalanceAfter\" = \"BalanceBefore\" + \"Delta\"");

                            t.HasCheckConstraint("CK_CurrencyChangeLogs_CurrencyType_Valid", "\"CurrencyType\" IN (1, 2)");

                            t.HasCheckConstraint("CK_CurrencyChangeLogs_Delta_NotZero", "\"Delta\" <> 0");

                            t.HasCheckConstraint("CK_CurrencyChangeLogs_ReasonType_Valid", "\"ReasonType\" IN (1, 2, 3, 4, 5, 6, 7, 8)");

                            t.HasCheckConstraint("CK_CurrencyChangeLogs_SourceId_NotEmpty", "length(btrim(\"SourceId\")) > 0");
                        });
                });

            modelBuilder.Entity("blueServer.Domain.Entities.Mail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "SentAt");

                    b.HasIndex("PlayerId", "SourceType", "SourceId")
                        .IsUnique();

                    b.ToTable("Mails", t =>
                        {
                            t.HasCheckConstraint("CK_Mails_ClaimedAt_After_SentAt", "\"ClaimedAt\" IS NULL OR \"ClaimedAt\" >= \"SentAt\"");

                            t.HasCheckConstraint("CK_Mails_ExpiresAt_After_SentAt", "\"ExpiresAt\" IS NULL OR \"ExpiresAt\" > \"SentAt\"");

                            t.HasCheckConstraint("CK_Mails_ReadAt_After_SentAt", "\"ReadAt\" IS NULL OR \"ReadAt\" >= \"SentAt\"");

                            t.HasCheckConstraint("CK_Mails_SourceId_NotEmpty", "length(btrim(\"SourceId\")) > 0");

                            t.HasCheckConstraint("CK_Mails_SourceType_Valid", "\"SourceType\" IN (0, 1, 2, 3)");
                        });
                });

            modelBuilder.Entity("blueServer.Domain.Entities.MailAttachment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<long>("MailId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MailId", "Type")
                        .IsUnique();

                    b.ToTable("MailAttachments", t =>
                        {
                            t.HasCheckConstraint("CK_MailAttachments_Amount_Positive", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("blueServer.Domain.Entities.OwnedCharacter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CharacterTemplateId")
                        .HasColumnType("integer");

                    b.Property<long>("Exp")
                        .HasColumnType("bigint");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("Star")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CharacterTemplateId");

                    b.HasIndex("PlayerId");

                    b.ToTable("OwnedCharacters");
                });

            modelBuilder.Entity("blueServer.Domain.Entities.Party", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PartyNo")
                        .HasColumnType("integer");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "PartyNo")
                        .IsUnique();

                    b.ToTable("Parties");
                });

            modelBuilder.Entity("blueServer.Domain.Entities.PartySlot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("OwnedCharacterId")
                        .HasColumnType("bigint");

                    b.Property<long>("PartyId")
                        .HasColumnType("bigint");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnedCharacterId");

                    b.HasIndex("PartyId", "OwnedCharacterId")
                        .IsUnique();

                    b.HasIndex("PartyId", "SlotIndex")
                        .IsUnique();

                    b.ToTable("PartySlots");
                });

            modelBuilder.Entity("blueServer.Domain.Entities.Player", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Gem")
                        .HasColumnType("integer");

                    b.Property<int>("Gold")
                        .HasColumnType("integer");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("blueServer.Domain.Entities.RewardGrantItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<long>("RewardGrantRecordId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RewardGrantRecordId", "Type")
                        .IsUnique();

                    b.ToTable("RewardGrantItems");
                });

            modelBuilder.Entity("blueServer.Domain.Entities.RewardGrantRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "RequestId")
                        .IsUnique();

                    b.ToTable("RewardGrantRecords");
                });

            modelBuilder.Entity("blueServer.Domain.Entities.StageClearRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ClearCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FirstClearedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastClearedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("StageTemplateId")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("StageTemplateId");

                    b.HasIndex("PlayerId", "StageTemplateId")
                        .IsUnique();

                    b.ToTable("StageClearRecords");
                });

            modelBuilder.Entity("blueServer.Domain.Entities.StageTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RewardGem")
                        .HasColumnType("integer");

                    b.Property<int>("RewardGold")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StageTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "1-1",
                            RewardGem = 10,
                            RewardGold = 100
                        });
                });

            modelBuilder.Entity("blueServer.Domain.Entities.CurrencyChangeLog", b =>
                {
                    b.HasOne("blueServer.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("blueServer.Domain.Entities.RewardGrantRecord", "RewardGrantRecord")
                        .WithMany()
                        .HasForeignKey("RewardGrantRecordId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Player");

                    b.Navigation("RewardGrantRecord");
                });

            modelBuilder.Entity("blueServer.Domain.Entities.Mail", b =>
                {
                    b.HasOne("blueServer.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("blueServer.Domain.Entities.MailAttachment", b =>
                {
                    b.HasOne("blueServer.Domain.Entities.Mail", "Mail")
                        .WithMany("Attachments")
                        .HasForeignKey("MailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mail");
                });

            modelBuilder.Entity("blueServer.Domain.Entities.OwnedCharacter", b =>
                {
                    b.HasOne("blueServer.Domain.Entities.CharacterTemplate", "CharacterTemplate")
                        .WithMany()
                        .HasForeignKey("CharacterTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("blueServer.Domain.Entities.Player", "Player")
                        .WithMany("OwnedCharacters")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterTemplate");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("blueServer.Domain.Entities.Party", b =>
                {
                    b.HasOne("blueServer.Domain.Entities.Player", "Player")
                        .WithMany("Parties")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("blueServer.Domain.Entities.PartySlot", b =>
                {
                    b.HasOne("blueServer.Domain.Entities.OwnedCharacter", "OwnedCharacter")
                        .WithMany()
                        .HasForeignKey("OwnedCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("blueServer.Domain.Entities.Party", "Party")
                        .WithMany("Slots")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnedCharacter");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("blueServer.Domain.Entities.RewardGrantItem", b =>
                {
                    b.HasOne("blueServer.Domain.Entities.RewardGrantRecord", "RewardGrantRecord")
                        .WithMany("Items")
                        .HasForeignKey("RewardGrantRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RewardGrantRecord");
                });

            modelBuilder.Entity("blueServer.Domain.Entities.RewardGrantRecord", b =>
                {
                    b.HasOne("blueServer.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("blueServer.Domain.Entities.StageClearRecord", b =>
                {
                    b.HasOne("blueServer.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("blueServer.Domain.Entities.StageTemplate", "StageTemplate")
                        .WithMany("ClearRecords")
                        .HasForeignKey("StageTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("StageTemplate");
                });

            modelBuilder.Entity("blueServer.Domain.Entities.Mail", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("blueServer.Domain.Entities.Party", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("blueServer.Domain.Entities.Player", b =>
                {
                    b.Navigation("OwnedCharacters");

                    b.Navigation("Parties");
                });

            modelBuilder.Entity("blueServer.Domain.Entities.RewardGrantRecord", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("blueServer.Domain.Entities.StageTemplate", b =>
                {
                    b.Navigation("ClearRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
