// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using blueServer.Infrastructure;

#nullable disable

namespace blueServer.Infrastructure.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260709044943_AddPartyTables")]
    partial class AddPartyTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("blueServer.Domain.Entities.CharacterTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CharacterTemplates");
                });

            modelBuilder.Entity("blueServer.Domain.Entities.OwnedCharacter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CharacterTemplateId")
                        .HasColumnType("integer");

                    b.Property<long>("Exp")
                        .HasColumnType("bigint");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("Star")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CharacterTemplateId");

                    b.HasIndex("PlayerId");

                    b.ToTable("OwnedCharacters");
                });

            modelBuilder.Entity("blueServer.Domain.Entities.Party", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PartyNo")
                        .HasColumnType("integer");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "PartyNo")
                        .IsUnique();

                    b.ToTable("Parties");
                });

            modelBuilder.Entity("blueServer.Domain.Entities.PartySlot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("OwnedCharacterId")
                        .HasColumnType("bigint");

                    b.Property<long>("PartyId")
                        .HasColumnType("bigint");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnedCharacterId");

                    b.HasIndex("PartyId", "OwnedCharacterId")
                        .IsUnique();

                    b.HasIndex("PartyId", "SlotIndex")
                        .IsUnique();

                    b.ToTable("PartySlots");
                });

            modelBuilder.Entity("blueServer.Domain.Entities.Player", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Gem")
                        .HasColumnType("integer");

                    b.Property<int>("Gold")
                        .HasColumnType("integer");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("blueServer.Domain.Entities.OwnedCharacter", b =>
                {
                    b.HasOne("blueServer.Domain.Entities.CharacterTemplate", "CharacterTemplate")
                        .WithMany()
                        .HasForeignKey("CharacterTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("blueServer.Domain.Entities.Player", "Player")
                        .WithMany("OwnedCharacters")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterTemplate");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("blueServer.Domain.Entities.Party", b =>
                {
                    b.HasOne("blueServer.Domain.Entities.Player", "Player")
                        .WithMany("Parties")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("blueServer.Domain.Entities.PartySlot", b =>
                {
                    b.HasOne("blueServer.Domain.Entities.OwnedCharacter", "OwnedCharacter")
                        .WithMany()
                        .HasForeignKey("OwnedCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("blueServer.Domain.Entities.Party", "Party")
                        .WithMany("Slots")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnedCharacter");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("blueServer.Domain.Entities.Party", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("blueServer.Domain.Entities.Player", b =>
                {
                    b.Navigation("OwnedCharacters");

                    b.Navigation("Parties");
                });
#pragma warning restore 612, 618
        }
    }
}
